### ISSUE TITLE
пiздец

### ISSUE THREAD

**Issue by nubovik01** [rldv1/ssdtoolpy#2]
![image](https://github.com/rldv1/ssdtoolpy/assets/50026919/acf175bc-5f5c-4acd-acc3-1ffd7906e05c)

**Comment by notawho** [comment]
всё возможно

**Comment by nubovik01** [comment]
> всё возможно

мяу)

**Comment by nubovik01** [comment]
> всё возможно

@notawho, мяу! :)

**Comment by rldv1** [comment]
very objective reason for opening issue.

**Comment by notawho** [comment]
самое забавное, что та "загадка" сделана не мной. семь три, ещё услышимся.

**Comment by nubovik01** [comment]
> very objective reason for opening issue.

@rldv1, true.
